#ifndef __CR_CONFIG_H__
#define __CR_CONFIG_H__

#define CONFIG_HAS_TCP_REPAIR
#define CONFIG_HAS_STRLCPY
#define CONFIG_HAS_STRLCAT
// CONFIG_HAS_PTRACE_PEEKSIGINFO is not set
#define CONFIG_HAS_SETPROCTITLE_INIT
#define CONFIG_HAS_TCP_REPAIR_WINDOW
#define CONFIG_HAS_MEMFD_CREATE
// CONFIG_HAS_OPENAT2 is not set
#define CONFIG_HAS_NO_LIBC_RSEQ_DEFS
#endif /* __CR_CONFIG_H__ */
